/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KustomKwizKreationRouteImport } from './routes/kustom-kwiz-kreation'
import { Route as ChronokwizOfTheDayRouteImport } from './routes/chronokwiz-of-the-day'
import { Route as ChronokwizHistoryRouteImport } from './routes/chronokwiz-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KustomKwizTopicRouteImport } from './routes/kustom-kwiz.$topic'
import { Route as ChronokwizByDateDateRouteImport } from './routes/chronokwiz-by-date.$date'

const KustomKwizKreationRoute = KustomKwizKreationRouteImport.update({
  id: '/kustom-kwiz-kreation',
  path: '/kustom-kwiz-kreation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronokwizOfTheDayRoute = ChronokwizOfTheDayRouteImport.update({
  id: '/chronokwiz-of-the-day',
  path: '/chronokwiz-of-the-day',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronokwizHistoryRoute = ChronokwizHistoryRouteImport.update({
  id: '/chronokwiz-history',
  path: '/chronokwiz-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KustomKwizTopicRoute = KustomKwizTopicRouteImport.update({
  id: '/kustom-kwiz/$topic',
  path: '/kustom-kwiz/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronokwizByDateDateRoute = ChronokwizByDateDateRouteImport.update({
  id: '/chronokwiz-by-date/$date',
  path: '/chronokwiz-by-date/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chronokwiz-history': typeof ChronokwizHistoryRoute
  '/chronokwiz-of-the-day': typeof ChronokwizOfTheDayRoute
  '/kustom-kwiz-kreation': typeof KustomKwizKreationRoute
  '/chronokwiz-by-date/$date': typeof ChronokwizByDateDateRoute
  '/kustom-kwiz/$topic': typeof KustomKwizTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chronokwiz-history': typeof ChronokwizHistoryRoute
  '/chronokwiz-of-the-day': typeof ChronokwizOfTheDayRoute
  '/kustom-kwiz-kreation': typeof KustomKwizKreationRoute
  '/chronokwiz-by-date/$date': typeof ChronokwizByDateDateRoute
  '/kustom-kwiz/$topic': typeof KustomKwizTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chronokwiz-history': typeof ChronokwizHistoryRoute
  '/chronokwiz-of-the-day': typeof ChronokwizOfTheDayRoute
  '/kustom-kwiz-kreation': typeof KustomKwizKreationRoute
  '/chronokwiz-by-date/$date': typeof ChronokwizByDateDateRoute
  '/kustom-kwiz/$topic': typeof KustomKwizTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chronokwiz-history'
    | '/chronokwiz-of-the-day'
    | '/kustom-kwiz-kreation'
    | '/chronokwiz-by-date/$date'
    | '/kustom-kwiz/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chronokwiz-history'
    | '/chronokwiz-of-the-day'
    | '/kustom-kwiz-kreation'
    | '/chronokwiz-by-date/$date'
    | '/kustom-kwiz/$topic'
  id:
    | '__root__'
    | '/'
    | '/chronokwiz-history'
    | '/chronokwiz-of-the-day'
    | '/kustom-kwiz-kreation'
    | '/chronokwiz-by-date/$date'
    | '/kustom-kwiz/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChronokwizHistoryRoute: typeof ChronokwizHistoryRoute
  ChronokwizOfTheDayRoute: typeof ChronokwizOfTheDayRoute
  KustomKwizKreationRoute: typeof KustomKwizKreationRoute
  ChronokwizByDateDateRoute: typeof ChronokwizByDateDateRoute
  KustomKwizTopicRoute: typeof KustomKwizTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kustom-kwiz-kreation': {
      id: '/kustom-kwiz-kreation'
      path: '/kustom-kwiz-kreation'
      fullPath: '/kustom-kwiz-kreation'
      preLoaderRoute: typeof KustomKwizKreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronokwiz-of-the-day': {
      id: '/chronokwiz-of-the-day'
      path: '/chronokwiz-of-the-day'
      fullPath: '/chronokwiz-of-the-day'
      preLoaderRoute: typeof ChronokwizOfTheDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronokwiz-history': {
      id: '/chronokwiz-history'
      path: '/chronokwiz-history'
      fullPath: '/chronokwiz-history'
      preLoaderRoute: typeof ChronokwizHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kustom-kwiz/$topic': {
      id: '/kustom-kwiz/$topic'
      path: '/kustom-kwiz/$topic'
      fullPath: '/kustom-kwiz/$topic'
      preLoaderRoute: typeof KustomKwizTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronokwiz-by-date/$date': {
      id: '/chronokwiz-by-date/$date'
      path: '/chronokwiz-by-date/$date'
      fullPath: '/chronokwiz-by-date/$date'
      preLoaderRoute: typeof ChronokwizByDateDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChronokwizHistoryRoute: ChronokwizHistoryRoute,
  ChronokwizOfTheDayRoute: ChronokwizOfTheDayRoute,
  KustomKwizKreationRoute: KustomKwizKreationRoute,
  ChronokwizByDateDateRoute: ChronokwizByDateDateRoute,
  KustomKwizTopicRoute: KustomKwizTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
