/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChronokwizOfTheDayRouteImport } from './routes/chronokwiz-of-the-day'
import { Route as IndexRouteImport } from './routes/index'

const ChronokwizOfTheDayRoute = ChronokwizOfTheDayRouteImport.update({
  id: '/chronokwiz-of-the-day',
  path: '/chronokwiz-of-the-day',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chronokwiz-of-the-day': typeof ChronokwizOfTheDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chronokwiz-of-the-day': typeof ChronokwizOfTheDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chronokwiz-of-the-day': typeof ChronokwizOfTheDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chronokwiz-of-the-day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chronokwiz-of-the-day'
  id: '__root__' | '/' | '/chronokwiz-of-the-day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChronokwizOfTheDayRoute: typeof ChronokwizOfTheDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chronokwiz-of-the-day': {
      id: '/chronokwiz-of-the-day'
      path: '/chronokwiz-of-the-day'
      fullPath: '/chronokwiz-of-the-day'
      preLoaderRoute: typeof ChronokwizOfTheDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChronokwizOfTheDayRoute: ChronokwizOfTheDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
